# Generated by Django 5.1.7 on 2025-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
